storage: ./storage

auth:
        bitbucket:
                allow: webitects-dev(contributor | admin | member), webitects-dev
                defaultMailDomain: webitects.com
                hashPassword: true
packages:
        '@*/*':
                allow_access: $all
                allow_publish: $authenticated
                proxy: npmjs
        '**':
                allow_access: $all
                allow_publish: $authenticated
                proxy: npmjs
